id: A6BC84EF8
title: CII_ยง 18
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:51:23.131414
  last_modified_at: 2022-03-01 23:51:23.131448
