id: A6BC84EF8
title: CXI_ยง 105
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:51:23.320388
  last_modified_at: 2022-03-01 23:51:23.320392
