id: A6BC84EF8
title: CVI_ยง 52
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:51:23.240042
  last_modified_at: 2022-03-01 23:51:23.240046
