id: A6BC84EF8
title: CVIII_ยง 78
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:51:23.216334
  last_modified_at: 2022-03-01 23:51:23.216337
