id: A6BC84EF8
title: CIX_ยง 87
type: translation
source_metadata:
  languages:
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 23:51:23.173865
  last_modified_at: 2022-03-01 23:51:23.173870
